site_name: SPM-iOS
use_directory_urls: false

nav:
- 'Teoría':
#    - 0. Introducción : 'teoria/introduccion-servicios-ios/introduccion-servicios-ios.md'-->
    - 1. Firma, aprovisionamiento y distribución de apps: 'teoria/firma-aprovisionamiento/firma-aprovisionamiento.md'
    - 2. Mapas y localización: 'teoria/mapas-localizacion/mapas-localizacion.md'
#    - 3. Notificaciones: 'teoria/notificaciones/notificaciones.md'
#    - 4. iCloud y CloudKit: 'teoria/icloud/icloud.md'
#    - 5. Anuncios: 'teoria/anuncios/anuncios.md'
#    - 6. Compras InApp: 'teoria/compras-in-app/compras-in-app.md'
#    - 5. Extensiones: 'teoria/extensiones/extensiones.md'
- 'Prácticas':
    - Práctica 1: 'practicas/aprovisionamiento/firma-aprovisionamiento.md'
    - Práctica 2: 'practicas/mapas/mapas-localizacion.md'
#    - Práctica 3: 'practicas/notificaciones/notificaciones.md'
#    - Práctica 4: 'practicas/icloud/icloud.md'
#    - Práctica 5: 'practicas/anuncios/anuncios.md'
#    - Práctica 5: 'practicas/extensiones/extensiones.md'

theme:
    language: es
    name: 'material'
    palette:
        primary: 'Teal'
        accent: 'Teal'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: 'imagenes/logo.png'

# Ponemos como idioma de búsqueda el inglés
# para conseguir que busque correctamente
# todas las palabras en castellano, sin eliminar
# los excesivos derivados que se definen en
# https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.es.js

extra:
    search:
        language: 'en'

markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
    - footnotes
    - meta
    - sane_lists
    - toc:
       permalink: true
       toc_depth: 3
    - pymdownx.superfences
